### PR TITLE
Add more error checking, prepare() to SQL statements. Fix SQL not req…

### PR DESCRIPTION
**Pull request by Enchiridion**
…uiring a single term from each category.

This should fix the error you were getting.  I also fixed a bug where posts with multiple terms for the same taxonomy could get picked, even if they didn't match all the taxonomies.  The SQL was only looking at the count of total matches, not the count of each match in each taxonomy.  So if you had 3 taxonomies (TaxA, TaxB, TaxC), and 3 terms from TaxA matched, but none from TaxB or TaxC, it would get picked.

### CODE REVIEW

**Comment by ajaydsouza** [comment]
Thanks for this. I've merged it and will report if there are any issues still.

**Comment by ajaydsouza** [comment]
I don't see any more issues/errors being generated. I assume the taxonomy only applies to Custom Post Types?

**Comment by Enchiridion** [comment]
It should work with any post type that CRP does.  I just modified how the taxonomy filtering was done.

**Comment by ajaydsouza** [comment]
I made some minor modifications in the code and pushed through a new version in the repository. One main change is this line changed to the below which also takes into account categories and tags.
`$selected_taxonomy_slugs = $taxonomies;
`

**Pull request merged**
